packages:
  branch_codenames:
    ruby2.0: trusty-unstable
    production: trusty-stable

jobs:
  ruby2.0-mxm-default:
    builder: "make"
    base: "quay.io/madebymany/build-bases:trusty"
    build_depends:
      - ruby2.0
    packages:
      - type: debian
        name: ruby2.0-mxm-default
        version: 2.0
        depends:
          - ruby2.0
        repos:
          - mxm-public
        target: install
