software_groups: &software
  - "base_trusty"

packages:
  branch_codenames:
    ruby2.0: unstable
    production: stable

packages:
  branch_codenames:
    master: unstable
    production: stable

jobs:
  ruby2.0-mxm-default:
    builder: "make"
    software_groups: *software
    base: "ubuntu:14.04"
    build_depends:
      - ruby2.0
    packages:
      - type: debian
        name: ruby2.0-mxm-default
        version: 2.0
        depends:
          - ruby2.0
        repos:
          - mxm-public
        target: install
