software_groups: &software
  - "base"

packages:
  branch_codenames:
    master: unstable
    production: stable

jobs:
  ruby:
    builder: "make"
    software_groups: *software
    base: "ubuntu:12.04"
    build_depends:
      - libreadline-dev
      - libssl-dev
      - openssl
    packages:
      - type: debian
        name: ruby2.0.0
        version: 2.0.0-p576
        conflicts:
          - ruby-2-mxm
        depends:
          - openssl
        repos:
          - mxm-public
        target: install
